ObjectLoss:
  name: ObjectLoss
  module: deeplodocus.app.losses.yolo
  weight: 1
  kwargs:
    iou_threshold: 0.5
    obj_weight: 10
BoxLoss:
  name: BoxLoss
  module: deeplodocus.app.losses.yolo
  weight: 1
  kwargs:
    iou_threshold: 0.5
ClassLoss:
  name: ClassLoss
  module: deeplodocus.app.losses.yolo
  weight: 1
  kwargs: {}


